version: "3.5"
services:
  kong-database:
    image: postgres:9.5
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: 123456789
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:latest
    command: "kong migrations up"
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: 123456789
    links:
      - kong-database
    depends_on:
      - kong-database

  navigation-kong:
    image: kong:latest
    restart: always
    depends_on: 
      - kong-migration
      - kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    environment:
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=123456789
      - KONG_PG_SSL=true
      - KONG_PG_SSL_VERIFY=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 5s
      timeout: 2s
      retries: 15

  navigation-1:
    image: trolland97/navigation:v1.0
    expose:
      - "10010"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10010"]
      interval: 5s
      timeout: 2s
      retries: 15

  navigation-2:
    image: trolland97/navigation:v2.0
    expose:
      - "10010"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10010"]
      interval: 5s
      timeout: 2s
      retries: 15